### ISSUE TITLE
Knora App Version not easily recognized and found

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#129]
I tried to find the Version of the System. I expected it in a menu "Info" or similar like in other software. 
Only with help from Flavie I found out, that the Verion information is in an one of those boxes but below the visible website part. 
I would wish for less text, boxes and such  on that page, but prezise 1-line information with links to further information. That way all I need to see I can do without scrolling...

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Additional context**

**Comment by mrivoal** [comment]
**Describe the bug**
I didn't found any `info button` on the home page. I was only able to see the Knora-app version info once I clicked on  the `Help` menu.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
I think the knora-app version should be displayed on the home page, with a single line giving the precise information. Besides, I don't think that the version info is relevant in the `Help` menu.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**
Add any other context about the problem here.

**Comment by flavens** [comment]
Rita - 
![image](https://user-images.githubusercontent.com/29532462/68579855-6925ef80-0475-11ea-98dc-e65e77c0bebf.png)

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-284](https://dasch.myjetbrains.com/youtrack/issue/DSP-284)
