### ISSUE TITLE
Timed automatic logout?

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#199]
After 5 days of break, I opened the Knora-App website again.
I found out, that I am still logged in and can use the functions with no restrictions.
Is this as designed?
I expected an automatic logout after a certain time

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.97

* Version Knora App, 1.6.2

**Additional context**

**Comment by flavens** [comment]
@kilchenmann this issue is now solved thanks to the 24-hour session allowed in the client side, right? or is there some settings to change in DSP-API?

**Comment by kilchenmann** [comment]
Yes, the session we use in old @knora/core was always valid for 24 hours. (This was already implemented before test phase). In DSP-UI it should still be the same value. After this time, it checks on knora-api, if the token is still valid. Because in knora, the session duration is longer. I thought 7 days? A user will automatically logged-out when knora's jwt is not valid anymore. In this case after 7 days.
