### ISSUE TITLE
App storage

### ISSUE THREAD

**Issue by flavens** [dasch-swiss/knora-app#40]
**Is your feature request related to a problem? Please describe.**
Where do we store the search queries / templates? What‘s about the resource collections? Is the knora-team able to expand the admin storage e.g. collection and search template (close to the user profile) OR do we have to implement an additional database?

**Describe the solution you'd like**
We can use the the key-value-store in Knora but it's not yet implemented. At the moment we can experiment with localStorage which is also kind of key-value-store...

**Describe alternatives you've considered**
MongoDB

**Additional context**
N.A.

**Comment by flavens** [comment]
Interesting tutorial: https://www.djamware.com/post/5c75d68880aca754f7a9d1ed/node-express-angular-7-graphql-and-mongodb-crud-web-app

**Comment by subotic** [comment]
We (knora-api) uses `redis` (basically a fast key-value store) for caching. The only thing that is missing, is for `knora-api` to expose an endpoint allowing providing key-value store features.

**Comment by janCstoffregen** [comment]
If you already want to start creating the routes for the backend, you can use an http interceptor in angular, create routes there and use the localstorage for now, here is an example:

https://github.com/cornflourblue/angular-6-registration-login-example/blob/master/src/app/_helpers/fake-backend.ts

You can migrate the routes to knora or node later and you can already start implementing everything you'd like to implement. @Vijeinath and I did the same.

inseri already has routes for user management and for storing queries, @Vijeinath implemented this ten months ago and it's generic.

You can find the models here: https://github.com/nie-ine/NIE-OS/tree/devel/backend/models
and you can find the routes here: https://github.com/nie-ine/NIE-OS/tree/devel/backend/routes

It would be nice if you had a look so that the same thing is not implemented twice, @Vijeinath has done most of the backend routes and models for the user management and the queries as well as the GUI for generic queries.

**Comment by flavens** [comment]
one [YouTrack epic](https://dasch.myjetbrains.com/youtrack/issue/DSP-144) has been opened about this issue

**Comment by janCstoffregen** [comment]
Dear @flavens, I'm still interested how you are planning to solve this, would you mind sketching your thoughts really quick?

**Comment by flavens** [comment]
@janCstoffregen there are several options on the table but we have to discuss with Ben and Ivan first. We have more important features to implement at the moment, I think we will go back on it in summer.
By the way, I will move all of our GitHub issues into YouTrack without adding any new details.
 I will let you know when we will status on one implementation.

**Comment by flavens** [comment]
this issue has been moved to YouTrack: https://dasch.myjetbrains.com/youtrack/issue/DSP-144
